-- Tabela de Estabelecimentos
CREATE TABLE "estabelecimentos" (
    "cnpj_basico" TEXT,
    "cnpj_ordem" TEXT,
    "cnpj_dv" TEXT,
    "identificador_matriz_filial" TEXT,
    "nome_fantasia" TEXT,
    "situacao_cadastral" TEXT,
    "data_situacao_cadastral" TEXT,
    "motivo_situacao_cadastral" TEXT,
    "nome_cidade_exterior" TEXT,
    "pais" TEXT,
    "data_inicio_atividade" TEXT,
    "cnae_fiscal_principal" TEXT,
    "cnae_fiscal_secundaria" TEXT,
    "tipo_logradouro" TEXT,
    "logradouro" TEXT,
    "numero" TEXT,
    "complemento" TEXT,
    "bairro" TEXT,
    "cep" TEXT,
    "uf" TEXT,
    "municipio" TEXT,
    "ddd_1" TEXT,
    "telefone_1" TEXT,
    "ddd_2" TEXT,
    "telefone_2" TEXT,
    "ddd_fax" TEXT,
    "fax" TEXT,
    "email" TEXT,
    "situacao_especial" TEXT,
    "data_situacao_especial" TEXT
);